# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Lovelace Academy
email: hello@lovelace.academy
subscribe: "https://academy.us7.list-manage.com/subscribe/post?u=2cc5f9357a349277646fbda76&id=34fa4be848"
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://learn.lovelace.academy/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: academylovelace
github_username:  lovelaceacademy
permalink: "/:categories/:title/"
# This is the menu.  Every item points to a category.  The order of
# items (starting with -) affects the order of menu items.  All posts
# sharing **exactly** the same category (case sensitive) are listed on
# each category.  For external links such as YouTube videos, add a
# `links` key.  For submenus, add a `categories` key with a list of
# categories.
menu:
- title: Getting Started
  icon: briefcase.png
  alt: briefcase
- title: Tokens
  icon: chat1.png
  alt: chat
- title: Smart Contracts
  icon: document.png
  alt: document
  categories:
  - title: Fundamentals
  - title: The Plutus Platform
  - title: Marlowe
- title: Videos
  icon: content.png
  alt: content
  links:
  - url: https://www.youtube.com/watch?v=ev75v-9LU5I
    title: Making Sense of Blockchain
    external: true
  - url: https://www.youtube.com/watch?v=sM0_V53_kGo
    title: The Cardano Revolution
    external: true
  - url: https://www.youtube.com/watch?v=mD1kAmP8K-M
    title: Interview with Dr Mihaela Ulieru
    external: true
  - url: https://www.youtube.com/watch?v=-k8E_xfLxnI
    title: Submitting a Catalyst Proposal
    external: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-slugify-categories

sass:
    sass_dir: scss

social:
- url: https://www.youtube.com/c/LovelaceAcademy/videos
  icon: social_youtube
  title: YouTube
- url: https://twitter.com/academylovelace
  icon: social_twitter
  title: Twitter
- url: https://github.com/lovelaceacademy
  icon: logo-github
  ion: true
  title: Github

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
