name: Jekyll
on:
- push
jobs:
  jekyll:
    runs-on: ubuntu-latest
    env:
      JEKYLL_ENV: development
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-2.7.3
          bundler-cache: true
      - name: build
        run: bundle exec jekyll build --trace
